-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 09:57:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecostoves
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecostoves` ;

-- -----------------------------------------------------
-- Schema ecostoves
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecostoves` DEFAULT CHARACTER SET utf8 ;
USE `ecostoves` ;

-- -----------------------------------------------------
-- Table `ecostoves`.`tbl_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecostoves`.`tbl_customer` ;

CREATE TABLE IF NOT EXISTS `ecostoves`.`tbl_customer` (
  `id_customer` INT(11) NOT NULL,
  `customer_name` VARCHAR(45) NULL DEFAULT NULL,
  `customer_address` VARCHAR(45) NULL DEFAULT NULL,
  `customer_county` VARCHAR(45) NULL DEFAULT NULL,
  `customer_phone` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecostoves`.`tbl_delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecostoves`.`tbl_delivery` ;

CREATE TABLE IF NOT EXISTS `ecostoves`.`tbl_delivery` (
  `id_delivery` INT(11) NOT NULL,
  `delivery_date` DATETIME NULL DEFAULT NULL,
  `courier` VARCHAR(45) NULL DEFAULT NULL,
  `tbl_customer_id_customer` INT(11) NOT NULL,
  PRIMARY KEY (`id_delivery`),
  INDEX `fk_tbl_delivery_tbl_customer1_idx` (`tbl_customer_id_customer` ASC),
  CONSTRAINT `fk_tbl_delivery_tbl_customer1`
    FOREIGN KEY (`tbl_customer_id_customer`)
    REFERENCES `ecostoves`.`tbl_customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecostoves`.`tbl_invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecostoves`.`tbl_invoice` ;

CREATE TABLE IF NOT EXISTS `ecostoves`.`tbl_invoice` (
  `id_invoice` INT(11) NOT NULL AUTO_INCREMENT,
  `subtotal` INT(11) NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL,
  `tbl_customer_id_customer` INT(11) NOT NULL,
  PRIMARY KEY (`id_invoice`),
  INDEX `fk_tbl_invoice_tbl_customer1_idx` (`tbl_customer_id_customer` ASC),
  CONSTRAINT `fk_tbl_invoice_tbl_customer1`
    FOREIGN KEY (`tbl_customer_id_customer`)
    REFERENCES `ecostoves`.`tbl_customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecostoves`.`tbl_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecostoves`.`tbl_orders` ;

CREATE TABLE IF NOT EXISTS `ecostoves`.`tbl_orders` (
  `id_orders` INT(11) NOT NULL,
  `tbl_customer_id_customer` INT(11) NOT NULL,
  PRIMARY KEY (`id_orders`),
  INDEX `fk_tbl_orders_tbl_customer_idx` (`tbl_customer_id_customer` ASC),
  CONSTRAINT `fk_tbl_orders_tbl_customer`
    FOREIGN KEY (`tbl_customer_id_customer`)
    REFERENCES `ecostoves`.`tbl_customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecostoves`.`tbl_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecostoves`.`tbl_payments` ;

CREATE TABLE IF NOT EXISTS `ecostoves`.`tbl_payments` (
  `paymentsID` INT(11) NOT NULL,
  `outstandingDebt` INT(11) NULL DEFAULT NULL,
  `tbl_invoice_id_invoice` INT(11) NOT NULL,
  PRIMARY KEY (`paymentsID`),
  INDEX `fk_tbl_payments_tbl_invoice1_idx` (`tbl_invoice_id_invoice` ASC),
  CONSTRAINT `fk_tbl_payments_tbl_invoice1`
    FOREIGN KEY (`tbl_invoice_id_invoice`)
    REFERENCES `ecostoves`.`tbl_invoice` (`id_invoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecostoves`.`tbl_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecostoves`.`tbl_products` ;

CREATE TABLE IF NOT EXISTS `ecostoves`.`tbl_products` (
  `id_products` INT(11) NOT NULL,
  `product_desc` VARCHAR(45) NULL DEFAULT NULL,
  `product_price` VARCHAR(45) NULL DEFAULT NULL,
  `tbl_orders_id_orders` INT(11) NOT NULL,
  `tbl_delivery_id_delivery` INT(11) NOT NULL,
  PRIMARY KEY (`id_products`),
  INDEX `fk_tbl_products_tbl_orders1_idx` (`tbl_orders_id_orders` ASC),
  INDEX `fk_tbl_products_tbl_delivery1_idx` (`tbl_delivery_id_delivery` ASC),
  CONSTRAINT `fk_tbl_products_tbl_orders1`
    FOREIGN KEY (`tbl_orders_id_orders`)
    REFERENCES `ecostoves`.`tbl_orders` (`id_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_products_tbl_delivery1`
    FOREIGN KEY (`tbl_delivery_id_delivery`)
    REFERENCES `ecostoves`.`tbl_delivery` (`id_delivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;